# Importing Libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Set display options to show all columns
pd.set_option('display.max_columns', None)

# Loading Data

In [3]:
# Load the data
yougov = pd.read_csv("Data/australia.csv")
oxcgrt = pd.read_csv("Data/OxCGRT_fullwithnotes_AUS_v1.csv")
owid = pd.read_csv("Data/owid-covid-data.csv")

C:\Users\Charmi Divecha\AppData\Local\Temp\ipykernel_16160\2727647840.py:2: DtypeWarning: Columns (0: i1_health, 1: i2_health, 2: i7a_health, 3: i13_health, 4: cantril_ladder, 5: m2, 6: vac_booster, 7: vac12_12, 8: vac12_13, 9: vac14_1, 10: vac14_2, 11: vac14_3, 12: child_age_1, 13: child_age_2, 14: child_age_3, 15: child_age_4, 16: child_age_5, 17: child_education_1, 18: child_education_2, 19: child_education_3, 20: child_education_4, 21: childvac, 22: combi_vac, 23: household_children, 24: Vent_1, 25: Vent_2, 26: Vent_3, 27: WAH_1, 28: WAH_2, 29: WAH_3, 30: WAH4, 31: WAH5, 32: WAH7_1, 33: WAH7_2, 34: WAH7_3, 35: WAH7_4, 36: WAH7_5, 37: WAH7_6, 38: WAH7_7, 39: WAH7_99, 40: WAH6, 41: V1_1, 42: V1_2, 43: V1_3, 44: V1_98, 45: V3_me, 46: V3_me_other, 47: V3_baby, 48: V3_baby_other, 49: V3_child2_4, 50: V3_child2_4_other, 51: V3_child5_17, 52: V3_child5_17_other, 53: V3_adult18, 54: V3_adult18_other, 55: V4_8, 56: V4_9, 57: V4_6, 58: V4_98, 59: V4_other, 60: SC_1_1, 61: SC_1_2, 62: SC_1_3, 63: SC_1_4, 64: SC_1_5, 65: SC_1_6, 66: SC_1_7, 67: SC_1_99, 68: SC_2, 69: SC_3_1, 70: SC_3_2, 71: SC_3_3, 72: SC_3_4, 73: SC_3_5, 74: SC_3_6, 75: SC_3_7, 76: SC_3_99, 77: vac_boost_1, 78: vac_boost_2, 79: vac12_booster_1, 80: vac12_booster_2, 81: vac12_booster_3, 82: vac12_booster_4, 83: vac12_booster_5, 84: vac12_booster_6, 85: vac12_booster_7, 86: vac12_booster_8, 87: vac12_booster_9, 88: vac12_booster_10, 89: vac12_booster_96, 90: vac12_booster_other, 91: vac_man_1, 92: vac_man_2, 93: vac_man_3, 94: vac_man_4, 95: vac_man_5, 96: vac_man_6, 97: vac_man_7, 98: vac_man_96, 99: vac_man_99, 100: q_other, 101: household_children_resp, 102: had_covid, 103: vac_boost_beyond, 104: future_1, 105: future_2, 106: had_covid_2, 107: long_covid, 108: future_3) have mixed types. Specify dtype option on import or set low_memory=False.
  yougov = pd.read_csv("Data/australia.csv")
C:\Users\Charmi Divecha\AppData\Local\Temp\ipykernel_16160\2727647840.py:3: DtypeWarning: Columns (0: CityName, 1: CityCode, 2: E3_Notes, 3: E4_Notes, 4: H4_Notes, 5: H5_Notes, 6: M1_Notes, 7: PopulationVaccinated) have mixed types. Specify dtype option on import or set low_memory=False.
  oxcgrt = pd.read_csv("Data/OxCGRT_fullwithnotes_AUS_v1.csv")

In [4]:
# YouGov data
yougov.head()

,RecordNo,endtime,qweek,i1_health,i2_health,i7a_health,i3_health,i4_health,i5_health_1,i5_health_2,i5_health_3,i5_health_4,i5_health_5,i5_health_99,i5a_health,i6_health,i7b_health,i8_health,i9_health,i10_health,i11_health,i12_health_1,i12_health_2,i12_health_3,i12_health_4,i12_health_5,i12_health_6,i12_health_7,i12_health_8,i12_health_9,i12_health_10,i12_health_11,i12_health_12,i12_health_13,i12_health_14,i12_health_15,i12_health_16,i12_health_17,i12_health_18,i12_health_19,i12_health_20,i13_health,i14_health_1,i14_health_2,i14_health_3,i14_health_4,i14_health_5,i14_health_6,i14_health_7,i14_health_8,i14_health_9,i14_health_10,i14_health_96,i14_health_98,i14_health_99,i14_health_other,d1_health_1,d1_health_2,d1_health_3,d1_health_4,d1_health_5,d1_health_6,d1_health_7,d1_health_8,d1_health_9,d1_health_10,d1_health_11,d1_health_12,d1_health_13,d1_health_98,d1_health_99,weight,age,gender,state,household_size,employment_status,WCRex2,WCRV_4,CORE_B2_4,cantril_ladder,PHQ4_1,PHQ4_2,PHQ4_3,PHQ4_4,m1_1,m1_2,m1_3,m1_4,m2,m3,m4_1,m4_2,m4_3,m4_4,m4_96,m4_99,m4_other,m5_1,m5_2,m6_1,m6_2,m6_3,m6_4,m6_5,m6_6,m6_7,m6_8,m6_96,m6_other,m7_1,m7_2,m7_3,m7_4,m7_5,m7_6,m7_8,m7_9,m7_10,m7_11,m8_1,m8_2,m8_3,m8_4,m8_5,m8_6,m8_7,m8_8,m8_96,m8_99,m8_other,m9_1,m9_2,m9_3,m9_4,m9_5,m9_6,m9_7,m10,m11,m12_1,m12_2,m12_3,m12_4,m12_5,m12_6,m12_7,m12_8,m12_96,m12_99,m12_other,m13_1,m13_2,m13_3,m13_4,m13_5,m13_6,m13_8,m13_9,m13_10,m13_11,v1,v2_1,v2_2,v2_3,v2_4,v2_5,v2_99,v3,v3_open,v4_1,v4_2,v4_3,v4_4,v4_5,v4_96,v4_99,v3_other,WCRex1,i12_health_21,i12_health_22,i12_health_23,i12_health_24,i12_health_25,r1_1,r1_2,r1_3,r1_4,r1_5,r1_6,r1_7,m7_other,m14_1,m14_2,m14_3,m14_4,m14_5,m14_6,m14_7,m14_8,m14_9,m14_10,m14_11,m14_96,m14_99,m14_open,i14_health_11,ct1_1,ct1_2,ct1b_1,ct1b_2,ct1b_3,ct1b_4,ct1b_5,ct1b_6,ct1b_7,ct1b_8,ct1b_9,ct1b_10,ct1b_11,ct1b_96,ct1b_99,ct1b_other,ct2,ct3,ct3_other,ct4,ct5_1,ct5_2,ct5_3,ct5_4,ct5_5,ct5_6,ct5_7,ct5_8,ct5_96,ct5_99,ct5_other,ct6_1,ct6_2,ct6_3,ct6_4,ct6_5,ct6_6,ct6_96,ct6_99,ct6_other,ct7_1,ct7_2,ct7_3,ct8_1,ct8_2,ct8_3,ct8_4,ct8_5,ct8_6,ct8_99,i12_health_26,ox1_1,ox1_2,ox3_1,ox3_2,ox3_3,ox3_4,ox3_5,ox3_6,ox5_1,ox5_2,ox6,ox4_1_1,ox4_2_1,ox4_3_1,ox4_4_1,ox4_5_1,ox4_6_1,ox4_7_1,ox4_8_1,ox4_9_1,ox4_10_1,ox4_11_1,w1,w2,w3,w4_1,w4_2,w4_3,w4_4,w4_5,w4_6,w4_7,w4_8,w4_9,w4_10,w4_11,w4_99,w4b,w5_1,w5_2,w5_3,w5_4,w5_5,w5_6,w5_7,w5_8,w5_9,w5_10,w5_11,w5_12,w5_13,w5_14,w5_15,w5_16,w5_96,w5_99,w6,w7,w9_1,w9_2,w9_3,w9_4,w9_5,disability,work1,work2,work3,work4,work5,work6,work7_1,work7_2,work7_3,work7_4,work7_5,work8,i12_health_27,i12_health_28,i12_health_29,Soc1_1,Soc1_2,Soc1_3,Soc2_1,Soc2_2,Soc2_3,Soc2_4,Soc2_5,Soc2_6,Soc2_open,vac_1,vac_2,vac2_1,vac2_2,vac2_3,vac2_4,vac2_5,vac2_6,vac_3,vac3_1,vac3_2,vac3_3,vac3_4,vac3_5,vac3_6,vac3_7,vac3_8,vac3_9,vac3_other,vac4,vac5,vac6,vac7,vac8,av1_1,av1_2,av1_3,av1_99,av2,r1_8,r1_9,r1_10,vac2_7,av3,vac,vac9,vac10_1,vac10_2,vac10_3,vac10_4,vac10_5,vac10_99,vac11,travel1_1,travel1_2,travel1_3,travel1_4,travel1_99,vac12_1,vac12_2,vac12_3,vac12_4,vac12_11,vac12_5,vac12_6,vac12_7,vac12_8,vac12_9,vac12_10,vac12_96,vac12_other,vac13,vac10_8,vac_booster,vac12_12,vac12_13,vac14_1,vac14_2,vac14_3,child_age_1,child_age_2,child_age_3,child_age_4,child_age_5,child_education_1,child_education_2,child_education_3,child_education_4,childvac,combi_vac,household_children,Vent_1,Vent_2,Vent_3,WAH_1,WAH_2,WAH_3,WAH4,WAH5,WAH7_1,WAH7_2,WAH7_3,WAH7_4,WAH7_5,WAH7_6,WAH7_7,WAH7_99,WAH6,V1_1,V1_2,V1_3,V1_98,V3_me,V3_me_other,V3_baby,V3_baby_other,V3_child2_4,V3_child2_4_other,V3_child5_17,V3_child5_17_other,V3_adult18,V3_adult18_other,V4_8,V4_9,V4_6,V4_98,V4_other,SC_1_1,SC_1_2,SC_1_3,SC_1_4,SC_1_5,SC_1_6,SC_1_7,SC_1_99,SC_2,SC_3_1,SC_3_2,SC_3_3,SC_3_4,SC_3_5,SC_3_6,SC_3_7,SC_3_99,vac_boost_1,vac_boost_2,vac12_booster_1,vac12_booster_2,vac12_booster_3,vac12_booster_4,vac12_booster_5,vac12_booster_6,vac12_booster_7,vac12_booster_8,vac12_booster_9,vac12_booster_10,vac12_booster_96,vac12_booster_other,vac_man_1,vac_man_2,vac_man_3,vac_man_4,vac_man_5,vac_man_6,vac_man_7,vac_man_96,vac_man_99,q_other,household_children_resp,had_covid,vac_boost_beyond,future_1,future_2,had_covid_2,long_covid,future_3
0,0,01/04/2020 16:12,week 1,1,1,0,"No, I have not","No, they have not",,,,,,,,,,,Yes,Somewhat easy,Very willing,Rarely,Always,Frequently,Always,Always,Always,Always,Always,,,Always,Always,Always,Always,Always,Frequently,Always,Frequently,Frequently,Always,6,,,,,,,,,,,,,,__NA__,,,,,,,,,,,,,,,,0.678531,44,Male,Queensland,2,Not working - looking for work,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,01/04/2020 16:12,week 1,0,6,2,"No, I have not","No, they have not",,,,,,,,,,,Yes,Somewhat difficult,Very willing,Not at all,Always,Frequently,Always,Always,Sometimes,Always,Always,,,Frequently,Frequently,Frequently,Always,Frequently,Rarely,Not at all,Not at all,Rarely,Frequently,20,,,,,,,,,,,,,,__NA__,,,,,,,,,,,,,,,,1.049460,66,Male,Victoria,1,Retired,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,01/04/2020 16:13,week 1,0,0,1,"No, I have not","Yes, and they have not received their results ...",,,,,,,,,,,Yes,Very easy,Very willing,Always,Always,Always,Always,Always,Sometimes,Sometimes,Always,Rarely,Always,Always,Always,Always,Always,Always,Frequently,Rarely,Not at all,Always,Always,10,No,No,No,No,No,No,No,No,No,No,No,No,Yes,__NA__,,,,,,,,,,,,,,,,1.271203,22,Male,Victoria,3,Working part time (8-34 hours a week),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,01/04/2020 16:16,week 1,2,20,1,"No, I have not","No, they have not",No,No,No,No,No,Yes,,,,,Yes,Somewhat difficult,Very willing,Always,Frequently,Frequently,Always,Always,Frequently,Frequently,Always,Not at all,Always,Always,Always,Always,Always,Frequently,Rarely,Not at all,Not at all,Not at all,Frequently,10,No,No,No,Yes,No,No,No,No,No,No,No,No,No,__NA__,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Yes,0.936885,45,Male,New South Wales,3,Working full time (35 or more hours per week),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,01/04/2020 16:21,week 1,2,0,0,,,,,,,,,,,,,Yes,Very difficult,Somewhat willing,Not at all,Always,Sometimes,Always,Always,Always,Always,Always,Always,Not at all,Always,Sometimes,Always,Always,Always,Sometimes,Always,Not at all,Rarely,Sometimes,4,No,No,No,No,No,No,No,No,No,No,No,No,Yes,__NA__,,,,,,,,,,,,,,,,0.762042,42,Female,Victoria,3,Working part time (8-34 hours a week),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# OxCGRT data
oxcgrt.head()

,CountryName,CountryCode,RegionName,RegionCode,CityName,CityCode,Jurisdiction,Date,C1E_School.closing,C1E_Flag,C1NV_School.closing,C1NV_Flag,C1V_School.closing,C1V_Flag,C1M_School.closing,C1M_Flag,C1_Notes,C2E_Workplace.closing,C2E_Flag,C2NV_Workplace.closing,C2NV_Flag,C2V_Workplace.closing,C2V_Flag,C2M_Workplace.closing,C2M_Flag,C2_Notes,C3E_Cancel.public.events,C3E_Flag,C3NV_Cancel.public.events,C3NV_Flag,C3V_Cancel.public.events,C3V_Flag,C3M_Cancel.public.events,C3M_Flag,C3_Notes,C4E_Restrictions.on.gatherings,C4E_Flag,C4NV_Restrictions.on.gatherings,C4NV_Flag,C4V_Restrictions.on.gatherings,C4V_Flag,C4M_Restrictions.on.gatherings,C4M_Flag,C4_Notes,C5E_Close.public.transport,C5E_Flag,C5NV_Close.public.transport,C5NV_Flag,C5V_Close.public.transport,C5V_Flag,C5M_Close.public.transport,C5M_Flag,C5_Notes,C6E_Stay.at.home.requirements,C6E_Flag,C6NV_Stay.at.home.requirements,C6NV_Flag,C6V_Stay.at.home.requirements,C6V_Flag,C6M_Stay.at.home.requirements,C6M_Flag,C6_Notes,C7E_Restrictions.on.internal.movement,C7E_Flag,C7NV_Restrictions.on.internal.movement,C7NV_Flag,C7V_Restrictions.on.internal.movement,C7V_Flag,C7M_Restrictions.on.internal.movement,C7M_Flag,C7_Notes,C8E_International.travel.controls,C8NV_International.travel.controls,C8V_International.travel.controls,C8EV_International.travel.controls,C8_Notes,E1_Income.support,E1_Flag,E1_Notes,E2_Debt.contract.relief,E2_Notes,E3_Fiscal.measures,E3_Notes,E4_International.support,E4_Notes,H1_Public.information.campaigns,H1_Flag,H1_Notes,H2_Testing.policy,H2_Notes,H3_Contact.tracing,H3_Notes,H4_Emergency.investment.in.healthcare,H4_Notes,H5_Investment.in.vaccines,H5_Notes,H6E_Facial.Coverings,H6E_Flag,H6NV_Facial.Coverings,H6NV_Flag,H6V_Facial.Coverings,H6V_Flag,H6M_Facial.Coverings,H6M_Flag,H6_Notes,H7_Vaccination.policy,H7_Flag,H7_Notes,H8E_Protection.of.elderly.people,H8E_Flag,H8NV_Protection.of.elderly.people,H8NV_Flag,H8V_Protection.of.elderly.people,H8V_Flag,H8M_Protection.of.elderly.people,H8M_Flag,H8_Notes,M1_Notes,V1_Vaccine.Prioritisation..summary.,V1_Notes,V2A_Vaccine.Availability..summary.,V2_Notes,V2B_Vaccine.age.eligibility.availability.age.floor..general.population.summary.,V2C_Vaccine.age.eligibility.availability.age.floor..at.risk.summary.,V2D_Medically..clinically.vulnerable..Non.elderly.,V2E_Education,V2F_Frontline.workers...non.healthcare.,V2G_Frontline.workers...healthcare.,V3_Vaccine.Financial.Support..summary.,V3_Notes,V4_Mandatory.Vaccination..summary.,V4_Notes,ConfirmedCases,ConfirmedDeaths,MajorityVaccinated,PopulationVaccinated,StringencyIndex_NonVaccinated,StringencyIndex_Vaccinated,StringencyIndex_SimpleAverage,StringencyIndex_WeightedAverage,GovernmentResponseIndex_NonVaccinated,GovernmentResponseIndex_Vaccinated,GovernmentResponseIndex_SimpleAverage,GovernmentResponseIndex_WeightedAverage,ContainmentHealthIndex_NonVaccinated,ContainmentHealthIndex_Vaccinated,ContainmentHealthIndex_SimpleAverage,ContainmentHealthIndex_WeightedAverage,EconomicSupportIndex
0,Australia,AUS,NaN,NaN,NaN,NaN,NAT_TOTAL,20200101,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,0.0,NaN,0.0,NaN,0,NaN,NaN,0,No cases reported/confirmed in Australia until...,0,No cases reported/confirmed in Australia until...,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,Same as C6,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NV,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Australia,AUS,NaN,NaN,NaN,NaN,NAT_TOTAL,20200102,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,0.0,NaN,0.0,NaN,0,NaN,NaN,0,NaN,0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NV,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Australia,AUS,NaN,NaN,NaN,NaN,NAT_TOTAL,20200103,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,0.0,NaN,0.0,NaN,0,NaN,NaN,0,NaN,0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NV,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Australia,AUS,NaN,NaN,NaN,NaN,NAT_TOTAL,20200104,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,0.0,NaN,0.0,NaN,0,NaN,NaN,0,NaN,0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NV,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Australia,AUS,NaN,NaN,NaN,NaN,NAT_TOTAL,20200105,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,0,NaN,0,NaN,NaN,0,NaN,0.0,NaN,0.0,NaN,0,NaN,NaN,0,NaN,0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NV,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
# OWID data
owid.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million,total_tests,new_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,positive_rate,tests_per_case,tests_units,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,stringency_index,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,54.42,18.6,2.58,1.34,1803.99,NaN,597.03,9.59,NaN,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,54.42,18.6,2.58,1.34,1803.99,NaN,597.03,9.59,NaN,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,54.42,18.6,2.58,1.34,1803.99,NaN,597.03,9.59,NaN,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,54.42,18.6,2.58,1.34,1803.99,NaN,597.03,9.59,NaN,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-09,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,54.42,18.6,2.58,1.34,1803.99,NaN,597.03,9.59,NaN,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN

In [7]:
# Data size
print("YouGov Data Size:", yougov.shape)
print("\nOxCGRT Data Size:", oxcgrt.shape)
print("\nOWID Data Size:", owid.shape)

YouGov Data Size: (53833, 513)

OxCGRT Data Size: (25208, 149)

OWID Data Size: (429435, 67)

# Data Cleaning

## YouGov Data

In [8]:
# Extracting and renaming YouGov columns
yougov_1 = yougov[[
    "endtime",
    "qweek",
    "weight",
    "age",
    "gender",
    "state",
    "household_size",
    "employment_status",
    
    # Behaviour outcomes
    "i12_health_1",   # mask wearing
    "i12_health_2",   # washed hands
    "i12_health_3",   # used sanitiser
    "i12_health_6",   # avoided going out
    "i12_health_8",   # avoided public transport
    "i12_health_15",  # avoided crowded areas
    
    # Self-isolation
    "i9_health",
    "i11_health",
    
    # Behaviour intensity / mobility
    "i13_health",
    "i7a_health",
    
    # Perception / behavioural drivers
    "r1_1",
    "r1_2",
    "r1_6",
    "r1_7",
    
    # Trust
    "WCRex1"
]].rename(columns={
    "endtime": "date",
    "qweek": "survey_week",
    "weight": "survey_weight",
    "age": "age",
    "gender": "gender",
    "state": "state",
    "household_size": "household_size",
    "employment_status": "employment_status",

    "i12_health_1": "mask_wearing",
    "i12_health_2": "wash_hands",
    "i12_health_3": "use_sanitiser",
    "i12_health_6": "avoid_going_out",
    "i12_health_8": "avoid_public_transport",
    "i12_health_15": "avoid_crowded_areas",

    "i9_health": "would_self_isolate",
    "i11_health": "willingness_self_isolate",

    "i13_health": "handwashing_frequency",
    "i7a_health": "times_left_home",

    "r1_1": "covid_dangerous_for_me",
    "r1_2": "likely_to_get_covid",
    "r1_6": "important_to_improve_health",
    "r1_7": "life_affected_by_covid",

    "WCRex1": "trust_in_government_handling"
})

In [9]:
# YouGov data info
yougov_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 53833 entries, 0 to 53832
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   date                          53833 non-null  str
 1   survey_week                   53833 non-null  str
 2   survey_weight                 53833 non-null  float64
 3   age                           53833 non-null  int64
 4   gender                        53833 non-null  str
 5   state                         53833 non-null  str
 6   household_size                53833 non-null  str
 7   employment_status             53833 non-null  str
 8   mask_wearing                  53833 non-null  str
 9   wash_hands                    53833 non-null  str
 10  use_sanitiser                 53833 non-null  str
 11  avoid_going_out               53833 non-null  str
 12  avoid_public_transport        53833 non-null  str
 13  avoid_crowded_areas           53833 non-null  str
 14  would_self_isolate            53833 non-null  str
 15  willingness_self_isolate      53833 non-null  str
 16  handwashing_frequency         53833 non-null  object
 17  times_left_home               53833 non-null  object
 18  covid_dangerous_for_me        53833 non-null  str
 19  likely_to_get_covid           53833 non-null  str
 20  important_to_improve_health   53833 non-null  str
 21  life_affected_by_covid        53833 non-null  str
 22  trust_in_government_handling  53833 non-null  str
dtypes: float64(1), int64(1), object(2), str(19)
memory usage: 9.4+ MB

In [10]:
# YouGov columns
yougov_1.columns

Index(['date', 'survey_week', 'survey_weight', 'age', 'gender', 'state',
       'household_size', 'employment_status', 'mask_wearing', 'wash_hands',
       'use_sanitiser', 'avoid_going_out', 'avoid_public_transport',
       'avoid_crowded_areas', 'would_self_isolate', 'willingness_self_isolate',
       'handwashing_frequency', 'times_left_home', 'covid_dangerous_for_me',
       'likely_to_get_covid', 'important_to_improve_health',
       'life_affected_by_covid', 'trust_in_government_handling'],
      dtype='str')

In [11]:
# Convert date to datetime format
yougov_1["date"] = pd.to_datetime(
    yougov_1["date"],
    format="%d/%m/%Y %H:%M",
    errors="coerce"
).dt.normalize()

In [12]:
# Select string/object columns
str_cols = yougov_1.select_dtypes(include=["object", "string"]).columns

# Remove leading and trailing whitespace
for col in str_cols:
    yougov_1[col] = yougov_1[col].astype("string").str.strip()
    
# Convert empty strings to missing values
yougov_1[str_cols] = yougov_1[str_cols].replace(r"^\s*$", pd.NA, regex=True)

In [13]:
# Unique values in each columns
cols = [
    "gender",
    "state",
    "household_size",
    "employment_status",
    "mask_wearing",
    "wash_hands",
    "use_sanitiser",
    "avoid_going_out",
    "avoid_public_transport",
    "avoid_crowded_areas",
    "would_self_isolate",
    "willingness_self_isolate",
    "covid_dangerous_for_me",
    "likely_to_get_covid",
    "important_to_improve_health",
    "life_affected_by_covid",
    "trust_in_government_handling"
]

for col in cols:
    print(f"\nColumn: {col}")
    print(yougov_1[col].dropna().unique().tolist())

Column: gender
['Male', 'Female']

Column: state
['Queensland', 'Victoria', 'New South Wales', 'Australian Capital Territory', 'Northern Territory', 'Western Australia', 'South Australia', 'Tasmania']

Column: household_size
['2', '1', '3', '4', '5', 'Prefer not to say', '8 or more', '6', "Don't know", '7']

Column: employment_status
['Not working - looking for work', 'Retired', 'Working part time (8-34 hours a week)', 'Working full time (35 or more hours per week)', 'Not working - not looking for work', 'Working part time (Less than 8 hours a week)', 'Unemployed', 'Full time employment', 'Not working', 'Part time employment']

Column: mask_wearing
['Rarely', 'Not at all', 'Always', 'Frequently', 'Sometimes']

Column: wash_hands
['Always', 'Frequently', 'Sometimes', 'Rarely', 'Not at all']

Column: use_sanitiser
['Frequently', 'Always', 'Sometimes', 'Not at all', 'Rarely']

Column: avoid_going_out
['Always', 'Sometimes', 'Frequently', 'Not at all', 'Rarely']

Column: avoid_public_transport
['Always', 'Sometimes', 'Not at all', 'Frequently', 'Rarely']

Column: avoid_crowded_areas
['Always', 'Frequently', 'Rarely', 'Sometimes', 'Not at all']

Column: would_self_isolate
['Yes', 'No', 'Not sure']

Column: willingness_self_isolate
['Very willing', 'Somewhat willing', 'Somewhat unwilling', 'Not sure', 'Neither willing nor unwilling', 'Very unwilling']

Column: covid_dangerous_for_me
['5', '6', '1 – Disagree', '3', '4', '7 - Agree', '2']

Column: likely_to_get_covid
['1 – Disagree', '4', '6', '3', '2', '7 - Agree', '5']

Column: important_to_improve_health
['3', '6', '5', '7 - Agree', '4', '1 – Disagree', '2']

Column: life_affected_by_covid
['3', '4', '6', '7 - Agree', '1 – Disagree', '5', '2']

Column: trust_in_government_handling
['Somewhat well', 'Very well', "Don't know", 'Somewhat badly', 'Very badly']

In [14]:
# Replace common text missing values
missing_like = [
    "Don't know",
    "Prefer not to say",
    "Not sure",
]

yougov_1 = yougov_1.replace(missing_like, pd.NA)

In [15]:
# Format column values
likert_cols = [
    "covid_dangerous_for_me",
    "likely_to_get_covid",
    "important_to_improve_health",
    "life_affected_by_covid"
]

for col in likert_cols:
    yougov_1[col] = (
        yougov_1[col]
        .astype("string")
        .str.extract(r"^\s*([1-7])", expand=False)
    )

In [16]:
# Clean household_size
yougov_1["household_size"] = (
    yougov_1["household_size"]
    .astype("string")
    .str.replace("8 or more", "8", regex=False)
)

In [17]:
# Define column groups
freq_cols = [
    "mask_wearing",
    "wash_hands",
    "use_sanitiser",
    "avoid_going_out",
    "avoid_public_transport",
    "avoid_crowded_areas",
]

yes_no_cols = [
    "would_self_isolate"
]

willing_cols = [
    "willingness_self_isolate"
]

trust_cols = [
    "trust_in_government_handling"
]

# Define mappings
freq_map = {
    "Not at all": 1,
    "Rarely": 2,
    "Sometimes": 3,
    "Frequently": 4,
    "Always": 5
}

yes_no_map = {
    "No": 0,
    "Yes": 1
}

willing_map = {
    "Very unwilling": 1,
    "Somewhat unwilling": 2,
    "Neither willing nor unwilling": 3,
    "Somewhat willing": 4,
    "Very willing": 5
}

trust_map = {
    "Very badly": 1,
    "Somewhat badly": 2,
    "Somewhat well": 3,
    "Very well": 4
}

In [18]:
# Apply mappings
for col in freq_cols:
    yougov_1[col] = yougov_1[col].map(freq_map).astype("Int64")

for col in yes_no_cols:
    yougov_1[col] = yougov_1[col].map(yes_no_map).astype("Int64")

for col in willing_cols:
    yougov_1[col] = yougov_1[col].map(willing_map).astype("Int64")

for col in trust_cols:
    yougov_1[col] = yougov_1[col].map(trust_map).astype("Int64")

In [19]:
# Convert to numeric data type
numeric_cols = [
    "household_size",
    "handwashing_frequency",
    "times_left_home",
    "covid_dangerous_for_me",
    "likely_to_get_covid",
    "important_to_improve_health",
    "life_affected_by_covid"
]

for col in numeric_cols:
    yougov_1[col] = yougov_1[col].astype("Int64")

In [20]:
# Convert to category data type
cat_cols = [
    "gender",
    "state",
    "employment_status",
    "survey_week"
]

for col in cat_cols:
    yougov_1[col] = yougov_1[col].astype("category")

In [21]:
# Value count
print("Handwashing frequecy:", (yougov_1["handwashing_frequency"] > 50).sum())
print("No. of times left home:", (yougov_1["times_left_home"] > 20).sum())

Handwashing frequecy: 212
No. of times left home: 38

In [22]:
# Replace unrealistic values with NaN
yougov_1.loc[yougov_1["handwashing_frequency"] > 50, "handwashing_frequency"] = np.nan
yougov_1.loc[yougov_1["times_left_home"] > 20, "times_left_home"] = np.nan

In [23]:
# YouGov data info
yougov_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 53833 entries, 0 to 53832
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   date                          53833 non-null  datetime64[us]
 1   survey_week                   53833 non-null  category
 2   survey_weight                 53833 non-null  float64
 3   age                           53833 non-null  int64
 4   gender                        53833 non-null  category
 5   state                         53833 non-null  category
 6   household_size                52474 non-null  Int64
 7   employment_status             53833 non-null  category
 8   mask_wearing                  53833 non-null  Int64
 9   wash_hands                    52827 non-null  Int64
 10  use_sanitiser                 53833 non-null  Int64
 11  avoid_going_out               53833 non-null  Int64
 12  avoid_public_transport        53833 non-null  Int64
 13  avoid_crowded_areas           53833 non-null  Int64
 14  would_self_isolate            48198 non-null  Int64
 15  willingness_self_isolate      51765 non-null  Int64
 16  handwashing_frequency         35720 non-null  Int64
 17  times_left_home               35894 non-null  Int64
 18  covid_dangerous_for_me        44810 non-null  Int64
 19  likely_to_get_covid           44810 non-null  Int64
 20  important_to_improve_health   32939 non-null  Int64
 21  life_affected_by_covid        32939 non-null  Int64
 22  trust_in_government_handling  44945 non-null  Int64
dtypes: Int64(16), category(4), datetime64[us](1), float64(1), int64(1)
memory usage: 8.8 MB

In [24]:
# Check missing values (count + percentage)
missing_count = yougov_1.isna().sum()
missing_percent = round(((missing_count / len(yougov_1)) * 100), 2)

missing_summary_yougov = pd.DataFrame({
    "Missing_Count": missing_count,
    "Missing_Percentage": missing_percent
}).sort_values(by="Missing_Count", ascending=False)

print("Missing values by column (Count & Percentage):")
display(missing_summary_yougov)

Missing values by column (Count & Percentage):

                              Missing_Count  Missing_Percentage
important_to_improve_health           20894               38.81
life_affected_by_covid                20894               38.81
handwashing_frequency                 18113               33.65
times_left_home                       17939               33.32
covid_dangerous_for_me                 9023               16.76
likely_to_get_covid                    9023               16.76
trust_in_government_handling           8888               16.51
would_self_isolate                     5635               10.47
willingness_self_isolate               2068                3.84
household_size                         1359                2.52
wash_hands                             1006                1.87
date                                      0                0.00
survey_week                               0                0.00
age                                       0                0.00
survey_weight                             0                0.00
state                                     0                0.00
gender                                    0                0.00
avoid_crowded_areas                       0                0.00
avoid_public_transport                    0                0.00
employment_status                         0                0.00
mask_wearing                              0                0.00
avoid_going_out                           0                0.00
use_sanitiser                             0                0.00

In [25]:
# Numeric columns
numeric_cols = [
    "household_size",
    "handwashing_frequency",
    "times_left_home"
]

# Ordinal columns
ordinal_cols = [
    "covid_dangerous_for_me",
    "likely_to_get_covid",
    "important_to_improve_health",
    "life_affected_by_covid",
    "trust_in_government_handling"
]

# Median imputation for numeric
for col in numeric_cols:
    yougov_1[col] = yougov_1[col].fillna(yougov_1[col].median())

# Mode imputation for ordinal
for col in ordinal_cols:
    mode_value = yougov_1[col].mode(dropna=True)[0]
    yougov_1[col] = yougov_1[col].fillna(mode_value)

In [26]:
# Check missing values AFTER
print("Missing values AFTER:")
print(yougov_1.isna().sum().sort_values(ascending=False))

Missing values AFTER:
would_self_isolate              5635
willingness_self_isolate        2068
wash_hands                      1006
age                                0
date                               0
survey_week                        0
survey_weight                      0
household_size                     0
state                              0
gender                             0
mask_wearing                       0
use_sanitiser                      0
avoid_going_out                    0
avoid_public_transport             0
employment_status                  0
avoid_crowded_areas                0
handwashing_frequency              0
times_left_home                    0
covid_dangerous_for_me             0
likely_to_get_covid                0
important_to_improve_health        0
life_affected_by_covid             0
trust_in_government_handling       0
dtype: int64

## OxCGRT Data

In [27]:
# Extracting and renaming OxCGRT columns
oxcgrt_1 = oxcgrt[[
    "Date",
    "RegionName",
    "Jurisdiction",

    # Core policy variables
    "H6M_Facial.Coverings",
    "C6M_Stay.at.home.requirements",
    "C7M_Restrictions.on.internal.movement",
    "C4M_Restrictions.on.gatherings",
    "C3M_Cancel.public.events",
    "C2M_Workplace.closing",
    "C5M_Close.public.transport",
    "C8EV_International.travel.controls",

    # Supporting policy variables
    "H1_Public.information.campaigns",
    "H2_Testing.policy",
    "H3_Contact.tracing",

    # Stringency
    "StringencyIndex_WeightedAverage"
]].rename(columns={
    "Date": "date",
    "RegionName": "region_name",
    "Jurisdiction": "jurisdiction",

    "H6M_Facial.Coverings": "mask_policy",
    "C6M_Stay.at.home.requirements": "stay_home_requirement",
    "C7M_Restrictions.on.internal.movement": "internal_movement_restriction",
    "C4M_Restrictions.on.gatherings": "gathering_restriction",
    "C3M_Cancel.public.events": "cancel_public_events",
    "C2M_Workplace.closing": "workplace_closing",
    "C5M_Close.public.transport": "public_transport_closure",
    "C8EV_International.travel.controls": "international_travel_controls",

    "H1_Public.information.campaigns": "public_information_campaign",
    "H2_Testing.policy": "testing_policy",
    "H3_Contact.tracing": "contact_tracing",

    "StringencyIndex_WeightedAverage": "stringency_index"
})

In [28]:
# Keep Australia-level total policy only
oxcgrt_1 = oxcgrt_1[
    (oxcgrt_1["region_name"].isna()) &
    (oxcgrt_1["jurisdiction"] == "NAT_TOTAL")
].copy()

# Drop extra column
oxcgrt_1 = oxcgrt_1.drop(columns=[
    "region_name",
    "jurisdiction"
])

In [29]:
# OxCGRT data info
oxcgrt_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1096 entries, 0 to 1095
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   date                           1096 non-null   int64
 1   mask_policy                    1096 non-null   int64
 2   stay_home_requirement          1096 non-null   int64
 3   internal_movement_restriction  1096 non-null   int64
 4   gathering_restriction          1096 non-null   int64
 5   cancel_public_events           1096 non-null   int64
 6   workplace_closing              1096 non-null   int64
 7   public_transport_closure       1096 non-null   int64
 8   international_travel_controls  1096 non-null   int64
 9   public_information_campaign    1096 non-null   int64
 10  testing_policy                 1096 non-null   int64
 11  contact_tracing                1096 non-null   int64
 12  stringency_index               1096 non-null   float64
dtypes: float64(1), int64(12)
memory usage: 111.4 KB

In [30]:
# Convert date to datetime format
oxcgrt_1["date"] = pd.to_datetime(oxcgrt_1["date"], format="%Y%m%d")

In [31]:
# OxCGRT data info
oxcgrt_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1096 entries, 0 to 1095
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   date                           1096 non-null   datetime64[us]
 1   mask_policy                    1096 non-null   int64
 2   stay_home_requirement          1096 non-null   int64
 3   internal_movement_restriction  1096 non-null   int64
 4   gathering_restriction          1096 non-null   int64
 5   cancel_public_events           1096 non-null   int64
 6   workplace_closing              1096 non-null   int64
 7   public_transport_closure       1096 non-null   int64
 8   international_travel_controls  1096 non-null   int64
 9   public_information_campaign    1096 non-null   int64
 10  testing_policy                 1096 non-null   int64
 11  contact_tracing                1096 non-null   int64
 12  stringency_index               1096 non-null   float64
dtypes: datetime64[us](1), float64(1), int64(11)
memory usage: 111.4 KB

In [32]:
# Sort first
oxcgrt_1 = oxcgrt_1.sort_values("date")

## OWID Data

In [33]:
# Extracting and renaming OWID columns
owid_1 = owid[[
    "location",
    "date",
    "new_cases_smoothed",
    "new_cases_smoothed_per_million",
    "new_deaths_smoothed",
    "reproduction_rate",
    "people_fully_vaccinated_per_hundred",
    "hosp_patients",
    "icu_patients"
]].rename(columns={
    "location": "country",
    "date": "date",
    "new_cases_smoothed": "new_cases_smoothed",
    "new_cases_smoothed_per_million": "new_cases_smoothed_per_million",
    "new_deaths_smoothed": "new_deaths_smoothed",
    "reproduction_rate": "reproduction_rate",
    "people_fully_vaccinated_per_hundred": "people_fully_vaccinated_per_hundred",
    "hosp_patients": "hospital_patients",
    "icu_patients": "icu_patients"
})

In [34]:
# Convert date and filter Australia
owid_1 = owid_1[owid_1["country"] == "Australia"].copy()

In [35]:
# OWID data info
owid_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1674 entries, 21776 to 23449
Data columns (total 9 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              1674 non-null   str
 1   date                                 1674 non-null   str
 2   new_cases_smoothed                   1669 non-null   float64
 3   new_cases_smoothed_per_million       1669 non-null   float64
 4   new_deaths_smoothed                  1668 non-null   float64
 5   reproduction_rate                    1028 non-null   float64
 6   people_fully_vaccinated_per_hundred  471 non-null    float64
 7   hospital_patients                    1347 non-null   float64
 8   icu_patients                         1347 non-null   float64
dtypes: float64(7), str(2)
memory usage: 117.8 KB

In [36]:
# Convert date to datetime format
owid_1["date"] = pd.to_datetime(owid_1["date"])

# Drop extra column
owid_1 = owid_1.drop(columns=["country"])

In [37]:
# OWID data info
owid_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1674 entries, 21776 to 23449
Data columns (total 8 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   date                                 1674 non-null   datetime64[us]
 1   new_cases_smoothed                   1669 non-null   float64
 2   new_cases_smoothed_per_million       1669 non-null   float64
 3   new_deaths_smoothed                  1668 non-null   float64
 4   reproduction_rate                    1028 non-null   float64
 5   people_fully_vaccinated_per_hundred  471 non-null    float64
 6   hospital_patients                    1347 non-null   float64
 7   icu_patients                         1347 non-null   float64
dtypes: datetime64[us](1), float64(7)
memory usage: 104.8 KB

In [38]:
# Check missing values
missing_summary_owid = owid_1.isna().sum().sort_values(ascending=False)
print("Missing values by column:")
print(missing_summary_owid)

Missing values by column:
people_fully_vaccinated_per_hundred    1203
reproduction_rate                       646
icu_patients                            327
hospital_patients                       327
new_deaths_smoothed                       6
new_cases_smoothed                        5
new_cases_smoothed_per_million            5
date                                      0
dtype: int64

In [39]:
# Sort by date
owid_1 = owid_1.sort_values("date").reset_index(drop=True)

In [40]:
# Interpolation for time-series variables
interp_cols = [
    "new_cases_smoothed",
    "new_cases_smoothed_per_million",
    "new_deaths_smoothed",
    "reproduction_rate",
    "hospital_patients",
    "icu_patients"
]

# Interpolate and fill edge missing values
owid_1[interp_cols] = (
    owid_1[interp_cols]
    .interpolate(method="linear", limit_direction="both")
)

# VVaccination: 0 before rollout, then interpolate
owid_1["people_fully_vaccinated_per_hundred"] = (
    owid_1["people_fully_vaccinated_per_hundred"]
    .fillna(0)
    .interpolate(method="linear", limit_direction="both")
)

In [41]:
# Check missing values AFTER
print("Missing values AFTER:")
print(owid_1.isna().sum().sort_values(ascending=False))

Missing values AFTER:
date                                   0
new_cases_smoothed                     0
new_cases_smoothed_per_million         0
new_deaths_smoothed                    0
reproduction_rate                      0
people_fully_vaccinated_per_hundred    0
hospital_patients                      0
icu_patients                           0
dtype: int64

# Exporting Data

In [42]:
# Saving the YouGov data as csv
csv_name = 'YouGov Data.csv'
yougov_1.to_csv(csv_name, index=False)

In [43]:
# Saving the OxCGRT data as csv
csv_name = 'OxCGRT Data.csv'
oxcgrt_1.to_csv(csv_name, index=False)

In [44]:
# Saving the OWID data as csv
csv_name = 'OWID Data.csv'
owid_1.to_csv(csv_name, index=False)